Ajout badge sur le README
lschaeffer313/domaine-nc-mobile pull request #65
Opened 2022-11-30 10:52 UTC by lschaeffer313

- Closes: #35

2022-11-30 12:00 UTC, adriens requested changes
C'est joli mais si on clique sur le badge, ça mène juste au badge.
Par exemple pour le Play Store ça redirige pas vers l'appli sur le store


![image](https://user-images.githubusercontent.com/5235127/204790889-9778b70f-57f7-4b81-a168-692192982733.png)

2022-11-30 12:18 UTC, HakumenNC requested changes

2022-11-30 12:18 UTC, HakumenNC commented on README.md
> +![Flutter](https://img.shields.io/badge/Google_Play-414141?style=for-the-badge&logo=google-play&logoColor=white)
c/c de l'alt text?

2022-12-01 10:55 UTC, HakumenNC approved these changes

2022-12-01 20:58 UTC, adriens approved these changes
Yes, beaucoup, beaucoup, mieux :zap:

2022-12-01 20:58 UTC, merged